"""Utilities to build GitHub review comments from analysis findings."""

from datetime import datetime
from typing import Dict, List

from ..models.finding import Finding


SEVERITY_ORDER = {
    "critical": 0,
    "high": 1,
    "medium": 2,
    "low": 3,
    "info": 4,
}

SEVERITY_EMOJI = {
    "critical": "🚨",
    "high": "🔴",
    "medium": "🟠",
    "low": "🟡",
    "info": "🔵",
}


class ReviewFormatter:
    MAX_FINDINGS = 20

    def generate_markdown(
        self,
        findings: List[Finding],
        summary: Dict[str, int],
        executive_summary: str | None = None,
    ) -> str:

        if not findings:
            return (
                "# ✅ PRLens Review\n\n"
                "No issues detected by configured analyzers."
            )

        grouped_findings = self._deduplicate_findings(findings)

        grouped_findings = sorted(
            grouped_findings,
            key=lambda item: (
                SEVERITY_ORDER.get(
                    (
                        item["finding"].severity or "info"
                    ).lower(),
                    99,
                ),
                item["finding"].file or "",
                item["finding"].start_line or 0,
            ),
        )

        grouped_findings = grouped_findings[
            : self.MAX_FINDINGS
        ]

        risk_rating = self._calculate_risk(summary)
        merge_status = self._merge_recommendation(summary)

        lines: List[str] = []

        # Header
        lines.append("# 🔍 PRLens Review")
        lines.append("")

        # Metrics
        lines.extend(
            [
                "| Metric | Value |",
                "|----------|----------|",
                f"| Risk Rating | {risk_rating} |",
                f"| Merge Status | {merge_status} |",
                f"| Total Findings | {len(findings)} |",
                f"| 🚨 Critical | {summary.get('critical', 0)} |",
                f"| 🔴 High | {summary.get('high', 0)} |",
                f"| 🟠 Medium | {summary.get('medium', 0)} |",
                f"| 🟡 Low | {summary.get('low', 0)} |",
                f"| 🔵 Info | {summary.get('info', 0)} |",
            ]
        )

        lines.append("")
        lines.append("---")
        lines.append("")

        if executive_summary:
            lines.append(executive_summary.strip())
            lines.append("")
            lines.append("---")
            lines.append("")

        severity_groups = {
            "critical": [],
            "high": [],
            "medium": [],
            "low": [],
            "info": [],
        }

        for item in grouped_findings:
            finding = item["finding"]

            severity = (
                finding.severity or "info"
            ).lower()

            severity_groups[severity].append(item)

        for severity in [
            "critical",
            "high",
            "medium",
            "low",
            "info",
        ]:

            items = severity_groups[severity]

            if not items:
                continue

            emoji = SEVERITY_EMOJI[severity]

            lines.append(
                f"## {emoji} {severity.capitalize()} Severity Findings ({len(items)})"
            )
            lines.append("")

            for item in items:
                lines.extend(
                    self._format_finding(item)
                )

        if len(findings) > self.MAX_FINDINGS:
            lines.append("")
            lines.append(
                f"_Showing {self.MAX_FINDINGS} findings._"
            )

        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append(
            f"_Generated by PRLens • {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}_"
        )

        return "\n".join(lines)

    def _calculate_risk(
        self,
        summary: Dict[str, int],
    ) -> str:

        if summary.get("critical", 0):
            return "🚨 Critical"

        if summary.get("high", 0):
            return "🔴 High"

        if summary.get("medium", 0):
            return "🟠 Medium"

        return "🟢 Low"

    def _merge_recommendation(
        self,
        summary: Dict[str, int],
    ) -> str:

        if summary.get("critical", 0):
            return "🚫 Block Merge"

        if summary.get("high", 0):
            return "❌ Changes Requested"

        if summary.get("medium", 0):
            return "⚠️ Review Carefully"

        return "✅ Ready For Review"

    def _deduplicate_findings(
        self,
        findings: List[Finding],
    ) -> List[dict]:

        grouped = {}

        for finding in findings:

            key = (
                finding.file,
                finding.start_line,
            )

            if key not in grouped:
                grouped[key] = {
                    "finding": finding,
                    "tools": set(),
                    "rules": set(),
                }

            grouped[key]["tools"].add(
                finding.tool.upper()
            )

            if finding.rule_id:
                grouped[key]["rules"].add(
                    finding.rule_id
                )

            current = grouped[key]["finding"]

            current_rank = SEVERITY_ORDER.get(
                (
                    current.severity or "info"
                ).lower(),
                99,
            )

            new_rank = SEVERITY_ORDER.get(
                (
                    finding.severity or "info"
                ).lower(),
                99,
            )

            if new_rank < current_rank:
                grouped[key]["finding"] = finding

        return list(grouped.values())

    def _format_finding(
        self,
        item: dict,
    ) -> List[str]:

        finding = item["finding"]

        severity = (
            finding.severity or "info"
        ).lower()

        emoji = SEVERITY_EMOJI.get(
            severity,
            "⚪",
        )

        tools = sorted(
            list(item["tools"])
        )

        rules = sorted(
            list(item["rules"])
        )

        return [
            "<details>",
            (
                f"<summary><strong>{finding.file}:{finding.start_line}</strong>"
                f" — {self._short_title(finding)}</summary>"
            ),
            "",
            f"**Severity:** {emoji} {severity.upper()}",
            "",
            "**Detected By**",
            ", ".join(tools),
            "",
            "**Rules**",
            ", ".join(rules)
            if rules
            else "N/A",
            "",
            "**Description**",
            finding.message
            or "No description available.",
            "",
            "</details>",
            "",
        ]

    def _short_title(
        self,
        finding: Finding,
    ) -> str:

        if not finding.message:
            return "Issue detected"

        title = finding.message.strip()

        if len(title) > 90:
            title = title[:90] + "..."

        return title