"""create_pr_reviews

Revision ID: 920c68b8f51f
Revises: 
Create Date: 2026-06-19 20:08:11.561642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '920c68b8f51f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pr_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('installation_id', sa.BigInteger(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('repo', sa.String(length=255), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('github_comment_id', sa.BigInteger(), nullable=False),
    sa.Column('last_commit_sha', sa.String(length=100), nullable=True),
    sa.Column('findings_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner', 'repo', 'pr_number', name='uq_pr_reviews_pr')
    )
    op.create_index(op.f('ix_pr_reviews_installation_id'), 'pr_reviews', ['installation_id'], unique=False)
    op.create_index(op.f('ix_pr_reviews_pr_number'), 'pr_reviews', ['pr_number'], unique=False)
    op.create_index(op.f('ix_pr_reviews_repo'), 'pr_reviews', ['repo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pr_reviews_repo'), table_name='pr_reviews')
    op.drop_index(op.f('ix_pr_reviews_pr_number'), table_name='pr_reviews')
    op.drop_index(op.f('ix_pr_reviews_installation_id'), table_name='pr_reviews')
    op.drop_table('pr_reviews')
    # ### end Alembic commands ###
